Update isismetadata.rst
USGS-Astrogeology/automated-metadata-generation pull request #10
Opened 2021-07-28 18:37 UTC by rfergason

2021-07-29 11:38 UTC, jlaura requested changes

2021-07-29 11:38 UTC, jlaura commented on docs/source/making_metadata/isismetadata.rst
> +The IsisFootPrintBlob container is useful for obtaining metadata information from an ISIS cube file and without having to retain that image file. In use, it can be excessive to ship ISIS cubes (that
'cube file and without' - remove 'and`? Sentence does not make sense with the 'and' in there.

2021-08-05 13:27 UTC, rfergason commented on docs/source/making_metadata/isismetadata.rst
> +The IsisFootPrintBlob container is useful for obtaining metadata information from an ISIS cube file and without having to retain that image file. In use, it can be excessive to ship ISIS cubes (that
Maybe I don't understand the benefit of the IsisFootPrintBlob container.  In reading the documentation, I thought it was useful for 1) obtaining metadata information and 2) because you can obtain metadata information you don't have to store or retain the image file.  With this understanding, the "and" makes sense to me.  How should the entire sentence be re-written to be more accurate?

2021-08-06 13:57 UTC, rfergason commented on docs/source/making_metadata/isismetadata.rst
> +The IsisFootPrintBlob container is useful for obtaining metadata information from an ISIS cube file and without having to retain that image file. In use, it can be excessive to ship ISIS cubes (that
After verbally discussing this sentence I think we came to an agreement regarding how to modify this sentence for clarity. I added a comma between these clauses as discussed.  Let me know if this helps communicate the intended information more clearly.

2021-08-06 14:00 UTC, rfergason commented on docs/source/making_metadata/isismetadata.rst
> +The IsisFootPrintBlob container is useful for obtaining metadata information from an ISIS cube file and without having to retain that image file. In use, it can be excessive to ship ISIS cubes (that
I actually rephrased the sentence instead.  Let me know if it's better.

2021-08-06 14:10 UTC, jlaura commented on docs/source/making_metadata/isismetadata.rst
> +The IsisFootPrintBlob container is useful for obtaining metadata information from an ISIS cube file, providing an option to no longer retain that image file. In use, it can be excessive to ship ISIS
typo 'informationthat' - otherwise looks good.

2021-08-06 14:40 UTC, merged